apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-mysql
  namespace: ecom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom-mysql
  template:
    metadata:
      labels:
        app: ecom-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.4
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecom-mysql-secret
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_DATABASE
              value: ecom

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: ecom-mysql-secret
                  key: MYSQL_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecom-mysql-secret
                  key: MYSQL_PASSWORD

          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data

