---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarqube-monitoring-secret
  namespace: sonarqube
spec:
  encryptedData:
    SONAR_MONITORING_PASSCODE: AgDUjVBF9XS53hcq6jQBYw/nmiFWklsxZRC/DkPQtmkaOfxuErScMaa2Mk4NOxT8j0demrWdApxBuKINwV7TIW3GKgNEEKvXN+AUix/OydQVun8OjadFgHfaq4o311IlZlJTKWs1KHxB1d1lBZ+654GV0Ay1HY1AmHYVtd0xW/O0HKyT8JGerBlxnSaWfxhGA6g25RTY3o9a1sIRkQUgE3RRIYLdTQ3h3BapHdOWKaI2M6VnkoaFavXRaO3nBoPw+oSnBh0Eq70n1LonRGW041yMFbpWAchbT6jK36/wNy58rBljFccN9t9YDDTszklCDxQigFf1IvonBpi+DXQnl5lji/M3NegOVF8+bidjuiJ+djwUybUmDcXeckSLy231ZtaTlBOPPk1HLzdA4C+TEDeyW7gygfbfduRnxMqi6UZyiNH9jh365bQ1R876bKGQcBOL8+p2DdUBqPkRTnUT1masMBCtNgiAVfWqlDoAl2Np9p19/eyj64rzKQPeGK1HEGtp+jDMEZh2ehlyEUATw7cMpe8ZCKMJ7Jl7AwhOo3axC4ZFtgH8VCySejirojFZ6Wi5qSqkAHzrghHDjbTBxZdobLiikxVgjtYBkaaOotvyBKwxA94wrcK+AClYFSz8EFREx4K8UnE6x2upUT7+RRPfIj2zRgravvV9lqCFl8xfQD5U/S2HDJmn2VD5jjrLTJ6qFr7Oo2tS09FPMyY4tDbuI0G9OJg=
  template:
    metadata:
      name: sonarqube-monitoring-secret
      namespace: sonarqube
