apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-postgresql
  namespace: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
