---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarqube-db-secret
  namespace: sonarqube
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgA8Th+o6+gv7/EX8pfUhyGmkcxga+9vyUf4jQXxqiBCU3Nd44V94drziFBJjmQB2I5I9XrZwwlBMKP0yaCp2LMaTwOExttrKo3j9lFpd8zcJSqJzkpAmnkOALur5el35hPdAGNnL7o0n2n6YYtaYeLI04qiBf4XxzhaAdj2wUIIYSQ7T8uaqRQ5B1NlpGltG0rDTaaMm04D+Lf0ZUf6cki6Fgu55fvs4atAizD0XlejBet0Pe0iZciTUZvvLwzj7F0R/OOxBX6kn99oiRBbN5FUmwQPRFJ8eUhWWXm6MloYhNZNP9PbY1PNbsQtlgN4huctrPt7DnkUrh42Q5m4TH0jc73EFSyMA+Z5MHPrD3zG6egoWIvQXlaBS2kM/8ytUlwQ5qcy2aFh+Tr8UJDayG94oTHlHARaIPQVK/86/QKESGl7zaqOHduAqR/VnbWjZma4IFVCqgwIM3WT3wLIB1gYBudWNd9jdsVzIQeiM3QYi+p4pooQQArqEFuwVQEYc51fLo97m5oA2Fht131J1ovBJQPDFn3vYaXo8O6yKEFbivFWJzX/PXNrE11+zds1upZygrDTUQh2i4hVMJ6Lo7gHGRctLoH4Ly4fxdJx+5ES3+w+5KTGgf3mJrhWa+bCeCSp1BdH+Ivlj6CpQ8pkLUmPy+d5NxGPqFoHzRk5qhUP++i2hIkxgAfcwbH6RgxweO0fsvG5
  template:
    metadata:
      name: sonarqube-db-secret
      namespace: sonarqube
