---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgDN9Ik7zCF5yYEfokfR/vNtr0rlNB9A2FWf/Ip2eWgsk4L7KjNl1IdFrVe+yRPb+9iigh0BhsumaRAzNWHlxRcMMWH9aueSdfIcmMBgwV5kCnL6H46mb15U+3agWtXOI0RhPcUgMft7vgFbYbLec8SGAAnmLFi7NeorHluUQC5hDjdXeOruRv/AfTeqqX27dvafnWcXvVOkNl/QRr5BQyaL/VIMi5VUTeoThuOGhm2uxEYpA/gnEh9ALMDX97WDU6EAHH6vEBRJm5OqE1TE18UDzezoz9BHFfMg5bOtmSaAi4WAnYuTPbqzL5bhKbH808vADO8NKyc1YV0N+1L2cFL3k3BTTH17lumsNMitypwt+77BxCEtMRtYbBdOCM2x+hZprcWL4h3V5ZTrpZwMbo7cyThulOtqHo66ZC/5x1C2kTp+ipj8+MiT44U8av3TJto+Qildci4v1TXUcDQ8l6td+hrHhvj5Dr3k8h2D0N15Ro8EN+FxC5W2XK+tsTa5k4WdiCQNqPAQAvy9HX5IqhEybCZmYv67Sx9MSiggdzkL+jsK9Xj92jqMZTyLdQuRwuGL+bCSccXg+v56CY70MZFAFVD2YI//QVXwXzfWp8z3C9ZEfLpTX0VSEaV4+GXjbU0939+oWiHy5qbIDG8BB1byOl0e9QPO8mPxtcu3L0ajaydwzitDzmx4nN1p3b4eO5LMqT0V/A==
    admin-user: AgCEqAuN4DIjvmpJVla6j6EPTTThfTTmA7j/sg1ydcwE1hbgC7CMGDd5LZxjeHmwdGY5ga+6jjfHov6pJbh3UVliUZ/yk9maTpCvtEg1b7yf52DzrufaBlPOctsYHUIJQm/1JFXx24swzLO2kISaKbv2aEWBJufE2XgNVlqFcTZrUXH1MWJYQ+bH7aQsKMaLf7bAkdItjb4uIKCXCgZ5IhHG4ymqgUgL4dq6VxnXbFwcZKAwDpOWUBjMpEL3f6APxEF7ntCSnfLxBQVi2iH+CQ+hdI4Wa0SndxsD9McxGBEcITX2lfux6AAVQhylI9KhquS9GAUf7J5WSunvp7NudQZM/R3LRXMzlPZOCWtHaPJXvg+V3nInNp3rCTtvPPT2+p6M0oHxJUWKiKFE5rpu56gDF6RXR9SZ1Eu0i4KD0HeArc0B3Xqlb/9tZW3Jq16OLfLWNOx39c5dNTDeSgf3PEXOttNH0frACW3iz68p0pxxV1nnvTgbgjrtdiVKx72aOW4cQJZvbEc/TBQaaLkOgnN7MzA+90zpYPnKrt6Rj10r306sN8TNq69wziWKyoqZ5eNfACpXpxDTCOEIqKYbkUd83ekLbdovxmtFr5IDjMzB+76mxl0nyUKMUzf/7CY4oAwV20LJbjMT0bTD32nrpjIZGZQEEPVOWAPXmgVQxzbMxlPZmUpl40k35PugU+giZfvMH/wIYw==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
